### ISSUE TITLE
Chart Suggestion

### ISSUE THREAD

**Issue by adrienbernede** [vsoch/llnl-contributors#2]
Hello!

To help grouping the project by similar "profile", I was thinking of a 2D chart, with:
- on X axis the percentage of external users
- on Y axis the total number of contributors
- the name of the project when hovering the data point

Maybe a bit like the one in the spack-proximity page.

That would help differentiate "small, mostly external projects" and "small mostly internal projects".

What do you think?

**Comment by vsoch** [comment]
oh that would be great! Just to clarify - you mean a scatter plot? I can put some time in the next few days to add it. Also a heads up that I'm developing a library called Contributor CI that will automate data extraction and plot generation, so we can add it there too.

**Comment by adrienbernede** [comment]
Yes, that is what I meant. Sorry, I am not good with plot nomenclature.

**Comment by vsoch** [comment]
haha no worries, you said "data point" which told me all I needed to know! :)

**Comment by vsoch** [comment]
How's this? https://vsoch.github.io/llnl-contributors/#scatterplot

![image](https://user-images.githubusercontent.com/814322/120722182-950c2a00-c48c-11eb-9369-537d0541bc58.png)

**Comment by adrienbernede** [comment]
Looks great I didn’t know there was such an even distribution on the percentage of external contributors.
Maybe we need a log scale on the y axis?

**Comment by vsoch** [comment]
Yeah I was thinking that too! I need to go for my run before it gets too late, but I'll update this later!

**Comment by vsoch** [comment]
How's this (not pushed lived yet)?

![image](https://user-images.githubusercontent.com/814322/120727147-06e97100-c497-11eb-85a9-2b8d198acd3f.png)

**Comment by adrienbernede** [comment]
I would say that it’s a good use of the surface: data points everywhere...

I was expecting clustering, log scale does spreads things apart though.

It also makes me realize that there is a finite set of values on the lower part, since we are talking about integer fractions. Hence the apparent symmetry

Somehow, the the conclusion is that there is no pattern. Except of course for the fact that when you have a lot of contributors, very likely most of them are from outside :).

We could add some value to it by coloring the dots based on another metric. Could be the number of stars, or maybe the number of lines of code, many possibilities depending on what we look for.

What do you think yourself?

**Comment by vsoch** [comment]
I don't find this particular plot very useful, at least compared to the others, so I'm not sure I can make good suggestions for updating it. Visually I kind of like the first version better, if I had to choose. Probably the one thing it does well (assuming the overlap isn't too bad) is putting all the repos in one space.

**Comment by adrienbernede** [comment]
I think I understand what you mean, and that was my goal: make small repos more visible. That's what I was not fund of with the other ones: they put a stress on repos with a large number of contributors, which are often the usual suspects (the most used, starred, etc.).

So what I like a 2D plot (not necessarily this one) is that all of them are visible.

Because of the overlapping, I think I like the log one better actually. There is probably still overlapping because it is likely some projects have the exact same values.

Of course the usefulness depends on what you wanted to achieve with this page, so feel free to ditch this plot if it does not serve your purpose.

**Comment by vsoch** [comment]
Oh I’ll definitely keep it! Is the log scale to your preference? I can push those changes.

**Comment by adrienbernede** [comment]
Yes the logscale, thanks!

**Comment by vsoch** [comment]
All set! Feel free to close the issue if we've addressed it.
